name       : python-iniparse
version    : 0.4
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/i/iniparse/iniparse-0.4.tar.gz : abc1ee12d2cfb2506109072d6c21e40b6c75a3fe90a9c924327d80bc0d99c054
license    : MIT
component  : programming.python
summary    : Module for accessing and modifying configuration data in INI files
description: |
    iniparse is an INI parser for Python which is API compatible with the
    standard library's ConfigParser, preserves structure of INI files
    (order of sections & options, indentation, comments, and blank lines
    are preserved when data is updated), and is more convenient to use.
builddeps  :
    - python-setuptools
rundeps    :
    - python-six
build      : |
    %apply_patches
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
